# SITE CONFIGURATION
title: Computing and Engineering Blog # your site title
author: Fidel Echevarria Corrales # You :P
description: > # Meta description of Homepage
  Computing and Engineering Blog by Fidel Echevarria Corrales.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://fidelechevarria.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Fidel Echevarria Corrales
  links:
    #- https://twitter.com/BenBalter
    #- https://www.facebook.com/ben.balter
    - https://www.linkedin.com/in/fidelechevarria
    #- https://plus.google.com/+BenBalter
    - https://github.com/fidelechevarria
    #- https://keybase.io/benbalter

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  Artificial Intelligence - Robotics - Optimization - Graphical Design

hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: fidel.echevarria.corrales@gmail.com # email for form submission

#twitter_username: jan_czizikow # replace with your_twitter_username or comment to remove link from footer
github_username:  fidelechevarria # replace with your_github_username or comment to remove link from footer
linkedin_username: fidelechevarria
#instagram_username: shanlongjj # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: fidelechevarria-github-io # to enable comments replace with your_disqus_shortname

google_tag_manager: GTM-W7LBXHH # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
